sudo: false
dist: bionic
language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

os:
  - linux

env:
  matrix:
    - PROFILES='-Pjacoco'

install:
    - mvn ${PROFILES} package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn ${PROFILES} test -B
